apiVersion: v1
kind: Service
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  ports:
    - port: 80
  selector:
    app: gitea
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pv-claim
  labels:
    app: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  selector:
    matchLabels:
      app: gitea
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitea
        tier: frontend
    spec:
      containers:
      - image: gitea:4.8-apache
        name: gitea
        env:
        - name: USER_UID
          value: 1000
        - name: USER_GID
          value: 1000
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: db:3306
        - name: DB_NAME
          value: gitea
        - name: DB_USER
          value: gitea
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: postgres-pass
              key: password
        ports:
        - containerPort: 80
          name: gitea
        volumeMounts:
        - name: gitea-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: gitea-persistent-storage
        persistentVolumeClaim:
          claimName: gitea-pv-claim