apiVersion: v1
kind: Service
metadata:
  name: gitea-postgres-svc
  namespace: scm
  labels:
    app: gitea
spec:
  ports:
    - port: 3306
  selector:
    app: gitea
    tier: postgres
  clusterIP: None
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres-pvc
  namespace: scm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-postgres
  namespace: scm
  labels:
    app: gitea
spec:
  selector:
    matchLabels:
      app: gitea
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitea
        tier: postgres
    spec:
      containers:
      - image: postgres:12-alpine
        name: postgres
        env:
        - name: POSTGRES_USER
          value: gitea
        - name: POSTGRES_DB
          value: password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pass
              key: password
        ports:
        - containerPort: 3306
          name: postgres
        volumeMounts:
        - name: gitea-postgres-persistent-storage
          mountPath: /data
      volumes:
      - name: gitea-postgres-persistent-storage
        persistentVolumeClaim:
          claimName: gitea-postgres-pvc
